# Generated by Django 5.2.4 on 2025-07-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Installation",
            fields=[
                ("gid", models.IntegerField(primary_key=True, serialize=False)),
                ("gml_id", models.CharField(max_length=100)),
                ("codeaiot", models.CharField(max_length=100)),
                ("raisonsociale", models.CharField(max_length=255)),
                ("adresse1", models.CharField(max_length=255)),
                ("codepostal", models.CharField(max_length=20)),
                ("codeinsee", models.CharField(max_length=20)),
                ("commune", models.CharField(max_length=255)),
                (
                    "statutseveso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "etatactivite",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("regimevigueur", models.CharField(max_length=100)),
                ("serviceaiot", models.CharField(max_length=100)),
                ("siret", models.CharField(blank=True, max_length=20, null=True)),
                ("geo_point_lat", models.FloatField()),
                ("geo_point_lon", models.FloatField()),
                ("bovins", models.BooleanField()),
                ("porcs", models.BooleanField()),
                ("volailles", models.BooleanField()),
                ("carriere", models.BooleanField()),
                ("eolienne", models.BooleanField()),
                ("industrie", models.BooleanField()),
                ("prioritenationale", models.BooleanField()),
                ("ied", models.BooleanField()),
                ("departement", models.CharField(max_length=100)),
            ],
        ),
    ]
