# Generated by Django 5.2.4 on 2025-07-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installation",
            name="adresse1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
