name: Django CI (SQLite)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: core.settings
      PYTHONPATH: backend

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install black flake8 isort

      - name: Run isort
        run: |
          isort --check --diff backend/

      - name: Run black
        run: |
          black --check backend/

      - name: Run flake8
        run: |
          flake8 backend/

      - name: Run migrations
        run: |
          python manage.py migrate
